id: apache-config
name: Apache Config file disclosure
severity: low

requests:
  - method: GET
    paths:
      - HOSTNAME/apache.conf
    patterns:
      - "contains(body, '<Directory') && contains(body, '</Directory>') && status_code == 200"
      - "contains(body, '<VirtualHost') && contains(body, '</VirtualHost>') && status_code == 200"
